server:
  port: 8080 # 所有后端请求的入口
logging:
  level:
    # 将 Gateway 的核心日志级别设置为 DEBUG
    org.springframework.cloud.gateway: DEBUG
    # (可选) 将 Reactor Netty 的日志也设为 DEBUG，可以看到更底层的网络交互
    reactor.netty.http.client: DEBUG
#    com.alibaba.nacos.client: DEBUG
spring:
  application:
    name: api-gateway
  #config:
    #import:
      # 引入共享配置
      #- "nacos:shared-config-ycr.yml"
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 54.219.180.170:8848
      #config:
        # 明确告诉 Nacos Config 默认的文件扩展名是 yml
        #file-extension: yml
        #group: DEFAULT_GROUP
    gateway:
      discovery:
        locator:
          enabled: true # 开启基于服务发现的路由功能
          lower-case-service-id: true # 将服务名转为小写路径，e.g., user-service -> /user-service/**
      routes:
        # 用户服务Swagger路由 - 必须放在通用路由之前
        # 用户服务Swagger路由 - 必须放在通用路由之前
        - id: user_swagger_ui
          uri: lb://user-service
          predicates:
            - Path=/api/user/swagger-ui/**
          filters:
            - StripPrefix=1
        
        - id: user_swagger_docs
          uri: lb://user-service
          predicates:
            - Path=/api/user/v3/api-docs/**
          filters:
            - StripPrefix=1
        
        - id: user_swagger_webjars
          uri: lb://user-service
          predicates:
            - Path=/api/user/webjars/**
          filters:
            - StripPrefix=1
        
        - id: user_swagger_config
          uri: lb://user-service
          predicates:
            - Path=/api/user/v3/api-docs/swagger-config
          filters:
            - StripPrefix=1
        
        # 问答服务Swagger路由 - 必须放在通用路由之前
        - id: qa_swagger_ui
          uri: lb://qa-service
          predicates:
            - Path=/api/qa/swagger-ui/**
          filters:
            - StripPrefix=1
        
        - id: qa_swagger_docs
          uri: lb://qa-service
          predicates:
            - Path=/api/qa/v3/api-docs/**
          filters:
            - StripPrefix=1
        
        - id: qa_swagger_webjars
          uri: lb://qa-service
          predicates:
            - Path=/api/qa/webjars/**
          filters:
            - StripPrefix=1
        
        - id: qa_swagger_config
          uri: lb://qa-service
          predicates:
            - Path=/api/qa/v3/api-docs/swagger-config
          filters:
            - StripPrefix=1
        
        # 用户服务路由
        - id: user_service_route
          uri: lb://user-service
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=1
        
        # JWT认证服务路由
        - id: auth_service_route
          uri: lb://user-service
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1
        
        # 问答服务路由
        - id: qa_service_route
          uri: lb://qa-service
          predicates:
            - Path=/api/qa/**
          filters:
            - StripPrefix=1
      
      # 全局CORS配置
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: 
              - "http://localhost:3000"
              - "http://127.0.0.1:3000"
              - "http://192.168.31.171:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600
    
    # 负载均衡配置
    loadbalancer:
      ribbon:
        enabled: false # 禁用Ribbon，使用Spring Cloud LoadBalancer
      retry:
        enabled: true # 启用重试机制
      health-check:
        initial-delay: 0 # 健康检查初始延迟
        interval: 25s # 健康检查间隔

# Actuator监控端点配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway # 暴露健康检查、信息和网关路由端点
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true # 启用网关端点
