server:
  port: 8081
spring:
  application:
    name: user-service-chl
  # cloud:
  #   nacos:
  #      discovery:
  #       server-addr: 18.144.11.177:8848
  datasource:
    url: jdbc:mysql://localhost:3306/ai_qa_system?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
jwt:
  secret: 63ffbc2b8d13ad5180ed7ae7c67f18c85d86046732fc9ced6a02a9d50abb1a03 # 替换为你的JWT密钥，建议至少32位长度
  expiration:
    ms: 86400000 # 可选，设置token过期时间（毫秒）

# SpringDoc配置
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    url: /v3/api-docs
    config-url: /v3/api-docs/swagger-config
    disable-swagger-default-url: true
