name: CI/CD for AI QA System

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test-backend:
    name: Build and Test Backend Services
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          # 匹配backend-services目录下的所有pom.xml，确保缓存正确
          key: ${{ runner.os }}-maven-${{ hashFiles('backend-services/**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # 关键修复：进入backend-services目录执行Maven命令（此处是父pom.xml所在目录）
      - name: Build and test all backend services
        run: mvn -B clean package
        working-directory: ./backend-services # 核心修改：指定包含pom.xml的目录

  build-and-push-images:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    needs: build-and-test-backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 构建API网关镜像（路径修正为backend-services下的子目录）
      - name: Build and push API Gateway image
        uses: docker/build-push-action@v5
        with:
          context: ./backend-services # 修正路径
          file: ./backend-services/api-gateway/Dockerfile # 修正路径
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ai-qa-api-gateway:latest

      # 构建用户服务镜像（路径修正）
      - name: Build and push User Service image
        uses: docker/build-push-action@v5
        with:
          context: ./backend-services # 修正路径
          file: ./backend-services/user-service/Dockerfile # 修正路径
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ai-qa-user-service:latest

      # 构建问答服务镜像（路径修正）
      - name: Build and push QA Service image
        uses: docker/build-push-action@v5
        with:
          context: ./backend-services # 修正路径
          file: ./backend-services/qa-service/Dockerfile # 修正路径
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ai-qa-qa-service:latest

      # 构建前端镜像
      - name: Build and push Frontend image
        uses: docker/build-push-action@v5
        with:
          build-args: |
            POSTGRES_URL=${{ secrets.POSTGRES_URL }}
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ai-qa-frontend:latest

      # 部署到EC2
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e  # 出错立即退出
            cd ~/ai-qa-system || { echo "部署目录不存在"; exit 1; }
            sudo docker-compose pull
            sudo docker-compose up -d --remove-orphans
            sudo docker image prune -f
